### ISSUE TITLE
not able to run the pipeline

### ISSUE THREAD

**Issue by rishikeshprl** [barentsen/dave#18]
Dear sir,
I have cloned the Dave repository to my home directory(on OS X El Capitan) and ran the checkRequirements.py it gave me results as 

"All requirements met!"
So then I ran the example as follows:-

from dave.pipeline import pipeline
cfg = pipeline.loadDefaultConfig()
pipeline.runOne(206103150, cfg)

But it gave me error as:-

WARN: This function is deprecated. See main.py instead.
Cannot Find Modshift Write Dir, /Users/paras/daveOutput 
Cannot Write to modshift directory /Users/paras/daveOutput 
Cannot Find Plotting Write Dir, /Users/paras/daveOutput 
Cannot Write to plotting directory /Users/paras/daveOutput 
Can not write to clip directory /Users/paras/daveOutput/
> /Users/paras/dave/pipeline/pipeline.py(166)checkDirExistTask()
-> raise IOError(msg)
(Pdb)

After that i realized that ihe code is not able to find the daveOutput/Modshift directory.
So I manually made '/Users/paras/daveOutput/Modshift' directory,then again i ran the code 

pipeline.runOne(206103150, cfg)

And got error as:-

'Required key centroid_col not found while looking up extract.centroid_col'
> /Users/paras/dave/pipeline/clipboard.py(231)get()
-> raise KeyError("Required key %s not found while looking up %s" %(k, keyString))
(Pdb)

I am not able to resolve both of the problems.
Please help me !!!!!!!!
Thanks in advance!
Rishi

**Comment by fergalm** [comment]
Hi Rishi,

So, despite our best efforts, DAVE is still very much under development, and we haven't put the effort into making it usable by the general public. You may find this a frustrating exercise, but we'll do our best to help.

Your first problem is fixed, it was just a case of creating those directories. 

Your second problem looks like a missing parameter in your configuration dictionary (cfg). Could you run the code, and when you get to the error, type bt to get a backtrace. Post the backtrace and that will help me figure out what's going wrong.


Thanks,

Fergal

**Comment by rishikeshprl** [comment]
Hi,
So i resolved last issues and got into newer ones,Actually for last one i changed the tasklist as 'extract.centroid_col'' is defined in the 'extractLightcurveFromTpfTask' so i added that one into tasklist and resolved the issue.

tasks = """checkDirExistTask serveTask extractLightcurveTask extractLightcurveFromTpfTask
        computeCentroidsTask rollPhaseTask cotrendSffDataTask detrendDataTask
        fblsTask trapezoidFitTask vetTask plotTask saveClip """.split()

Now i am getting the errors in vetTask,which is as follows:-
dy =

 Columns 1 through 6:

   0.0011595   0.0012338   0.0013013   0.0013669   0.0013745   0.0013885

 Columns 7 through 12:

   0.0013989   0.0014048   0.0014122   0.0014186   0.0014432   0.0014460

 Columns 13 through 15:

   0.0014468   0.0014597   0.0014639

'float' object is not iterable
> /Users/paras/dave/lpp/calcLPPoctave.py(70)fergalVersion()
-> time,flux,period,duration,phase,mapFile)
(Pdb) bt
  /Users/paras/dave/pipeline/task.py(105)wrapperForTask()
-> clip = func(*args, **kwargs)
  /Users/paras/dave/pipeline/pipeline.py(521)lppMetricTask()
-> period_days, duration_hrs, phase_bkjd)
> /Users/paras/dave/lpp/calcLPPoctave.py(70)fergalVersion()
-> time,flux,period,duration,phase,mapFile)
(Pdb) n
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dave/pipeline/pipeline.py", line 51, in runOne
    clip = f(clip)
  File "dave/pipeline/task.py", line 114, in wrapperForTask
    raise e
TypeError: 'float' object is not iterable.

I am not able to resolve this.

thanks,
Rishi
